### PR TITLE
fix: event types mixed up and add both types of events

### PR DESCRIPTION
**Pull request by bdw617**
from chatgpt, looks correct, we want to make sure we have the detail to make decisions to recreate a docker pull secret based on them changing remotely (ECR). The code currently gives you the correct object, but typed to the old object type causing mismatching.

---

### Differences between CoreV1Event and EventV1Event in Kubernetes

`CoreV1Event` and `EventV1Event` in Kubernetes refer to different versions and structures of events. Below is a comparison of the two:

#### CoreV1Event (`v1.Event`):
- Part of the `core/v1` API group.
- The original event resource type, present since early Kubernetes versions.
- Commonly used and interacted with via `kubectl get events`.
- Events are used primarily for debugging and do not guarantee comprehensive information about the cluster state.

#### EventV1Event (`events.k8s.io/v1.Event`):
- Introduced in later Kubernetes versions, starting as `events.k8s.io/v1beta1` in Kubernetes 1.10 and graduating to `events.k8s.io/v1` in Kubernetes 1.19.
- Provides an improved structure and additional features over `CoreV1Event`.
- Aims to offer more context and detailed information about events, enhancing the understanding of the cluster state.
- Features include event de-duplication and better event aggregation.

**Key Differences**:
- The primary differences lie in the API version and the details and structure of the event information.
- `EventV1Event` is preferable for more detailed event information and newer Kubernetes clusters.
- `CoreV1Event` is widely used for basic event information and is compatible with older Kubernetes versions.

**Considerations**:
- Choose based on the Kubernetes cluster version and the level of event detail required.
- For basic use cases, `CoreV1Event` is generally sufficient.
- For advanced event tracking and analysis, `EventV1Event` might be more suitable.

---

You can use this Markdown-formatted response for documentation purposes or any other suitable application.

### CODE REVIEW

**Review by jeff-mccoy — COMMENTED** [review]
It looks like we weren't actually exposing CoreV1Event at all before properly based on this--is there a reason to expose both or will events.k8s.io give us everything that Core V1 had?

**Comment by bdw617** [comment]
if we decide to expose both as we should, how do you like this?
...
  CoreV1Event as CoreEvent,
  EventsV1Event as Event,
---

**Comment by bdw617** [comment]
more recent event (now called Event)  you can see here `kubectl explain --api-version='events.k8s.io/v1' event`
older event (now called CoreEvent) you can see here: `kubectl explain event`

**Review by jeff-mccoy — APPROVED** [review]
lgtm, thx

**Pull request merged**
