### PR TITLE
feat: replace call

### LINKED ISSUE #51: Support for `kubectl replace`
### Is your feature request related to a problem? Please describe.

For circumstances when certainty is needed that no changes have been made to a resource between reading and updating. Helps when things are competing for the same resource.

### Describe the solution you'd like

- **Given** a resource is fetched with a `resourceVersion`
- **When** an update is created to that resource and the resourceVersion _has changed_
- **Then** the update is rejected.

```
Error from server (Conflict): error when replacing "STDIN": Operation cannot be fulfilled on configmaps "so": the object has been modified; please apply your changes to the latest version and try again
```

### Additional context
Came out of a convo with @bburky when ideating on potential ways  add DB semantics of ETCD around an issue thatn @bdw617 was having where he needs a transactional style data store.

### PR DESCRIPTION
**Pull request by cmwylie19**
# Description

Replace functionality to throw error during update of a resource if `resourceVersion` changed

# Related Issue
Fixes #51 

# Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

### CODE REVIEW

**Comment by cmwylie19** [comment]
This seems to work as expected:

When changing the resource version replace does not work: `k create cm test --from-literal=a=a`

image

image


If you do not change the resource version replace does work;

image


```bash
 > k get cm so -oyaml
apiVersion: v1
data:
  a: a
  pepr: was-not-here
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-25T20:09:32Z"
  name: so
  namespace: default
  resourceVersion: "1033"
  uid: 4d38223b-7ade-4053-8c66-f5308699ba6c
  ```

**Comment by jeff-mccoy** [comment]
We had something similar to this before `.Apply()`, this feels more like an `update` vs `replace`. The replace previously would update or delete/update iirc. Curious your thoughts and perhaps a bit more detail on the scenario.

**Comment by cmwylie19** [comment]
> We had something similar to this before `.Apply()`, this feels more like an `update` vs `replace`. The replace previously would update or delete/update iirc. Curious your thoughts and perhaps a bit more detail on the scenario.

The reason i called it replace is to mimic `kubectl replace` although i see your point about `Update`.

So the initial scenario involved a conversation during office hours where Barry wanted to use the store in a very transactional way with fast and frequent changes. It was not working the way he expected and Blake suggested using something similar to `kubectl replace` as a store alternative to still get a "store" DB semantics out of ETCD. He would go a `get` on an object, and would need a guarantee that the object got was the latest before making an more updates to the object.

I'm running into a secondary place where I need this functionality on the `OnSchedule` flow for Pepr.  The OnSchedule reads the store on boot to see if there is a pending interval incase there was a restart. I write the scheduled task to the store and update on each interval to track completions. the problem I am running into is that I am finding that the store is not there yet sometimes, so it may make sense to just write to a secret or cm (Because I don't want to write a new store resources from the OnSchedule).  Seems like using this `replace or update` where I am guaranteed that the latest object read is the last will be a nice way to ensure i am correctly tracking my completions, and I can immediately create a `CM` or `Secret` to use as my data store


```json
    data: {
      "kind": "Status",
      "apiVersion": "v1",
      "metadata": {},
      "status": "Failure",
      "message": "peprstores.pepr.dev \"pepr-static-test-store\" not found",
      "reason": "NotFound",
      "details": {
        "name": "pepr-static-test-store",
        "group": "pepr.dev",
        "kind": "peprstores"
      },
      "code": 404
    }
```

**Comment by bburky** [comment]
This looks good. Yes naming is a little confusing, but this matches `kubectl`. I'm not sure if the API binding call this "replace" too, might be good to check. `kubectl` also has `replace --force` which does a delete first then a create, don't think these bindings need it, but mentioning it for completeness.

As I mentioned, the feature in this PR lets you do conpare-and-swap against k8s/etcd. Which is good because we don't yet have an atomic store or a leader or anything. Its usually not a big deal, but this is a good escape hatch to access what k8s already has and do atomic operations.

**Comment by cmwylie19** [comment]
closing this for now, if we need it in the future we will re-open it

**Pull request closed without merging**
